---
- name: "Automated Tn4 Deployment (see: https://github.com/yamaoka-kitaguchi-lab/tn4-edges-deploy)"
  hosts: all
  gather_facts: no

  roles:
    - role: juniper
      when: manufacturer == "juniper"

    - role: cisco
      when: manufacturer == "cisco"
