---
- import_tasks: migrate.yml
  tags:
    - migrate
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli

- import_tasks: overwrite.yml
  tags:
    - overwrite
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli