---
- name: Display all variables and facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags:
    - develop
    - verbose

- name: Show version
  connection: network_cli
  tags:
    - develop
    - verbose

- name: Enable NETCONF
  connection: network_cli

- name: Create pre-snapshots
  connection: netconf
  tags:
    - nondry

- name: Check template rendering result
  debug:
    msg: "{{ lookup('template', 'interface.cfg.j2') }}"
  tags:
    - develop
    - rendering

- name: Update interface configurations
  connection: netconf
  vars:
    ansible_command_timeout: 60

- name: Create post-snapshots
  connection: netconf
  tags:
    - nondry
