---
- name: Display all variables and facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags:
    - develop
    - verbose

- name: Gather all legacy facts
  ios_facts:
    gather_subset: all
  tags:
    - develop
    - verbose

- name: Create pre-snapshots
  ios_config:
    backup: yes
    backup_options:
      filename: "{{ hostname }}_before.cfg"
      dir_path: "backup/cisco_config.{{ datetime }}"
  tags:
    - nondry

- name: Update VLAN database
  ios_vlans:
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vid }}"
        state: active
        shutdown: disabled
    state: overridden
  loop: "{{ vlans }}"

- name: Update interface description and status
  ios_interfaces:
    config:
      - name: "{{ item.key }}"
        description: "{{ item.value.description }}"
        enabled: "{{ item.value.enabled }}"
    state: replaced
  loop: "{{ lookup('dict', interfaces) }}"

- name: Update interface VLAN (1/3) - activating access VLAN
  ios_l2_interfaces:
    config:
      - name: "{{ item.key }}"
        access:
          vlan: "{{ item.value.vid[0] }}"
    state: replaced
  when: "{{ item.value.vlan_mode }} == 'access'"
  loop: "{{ lookup('dict', interfaces) }}"

- name: Update interface VLAN (2/3) - activating trunk VLAN
  ios_l2_interfaces:
    config:
      - name: "{{ item.key }}"
        trunk:
          allowed_vlans: "{{ item.value.vids|join(',') }}"
          encapsulation: dot1q
    state: replaced
  when: "{{ item.value.vlan_mode }} == 'trunk'"
  loop: "{{ lookup('dict', interfaces) }}"

- name: Update interface VLAN (3/3) - activating native VLAN
  ios_l2_interfaces:
    config:
      - name: "{{ item.key }}"
        trunk:
          native_vlan: "{{ item.value.native_vid }}"
          encapsulation: dot1q
    state: merged
  when: "{{ item.value.vlan_mode }} == 'trunk' and {{ item.value.native_vid }}"
  loop: "{{ lookup('dict', interfaces) }}"

- name: Create post-snapshots
  ios_config:
    backup: yes
    backup_options:
      filename: "{{ hostname }}_after.cfg"
      dir_path: "backup/cisco_config.{{ datetime }}"
  tags:
    - nondry
