---
- name: Display all variables and facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags:
    - develop
    - verbose

- name: Show version
  connection: network_cli
  junos_command:
    commands: show version
  tags:
    - develop
    - verbose

- name: Enable NETCONF
  connection: network_cli
  junos_netconf:

- name: Create backup directory
  ansible.builtin.file:
    path: "backup/juniper_config.{{ datetime }}"
    state: directory
  register: local_dir
  delegate_to: localhost
  tags:
    - nondry

- name: Create pre-snapshots
  connection: netconf
  junos_config:
    backup: yes
    backup_options:
      filename: "{{ hostname }}_before.cfg"
      dir_path: "backup/juniper_config.{{ datetime }}"
  tags:
    - nondry

- name: Check template rendering result (Edge)
  debug:
    msg: "{{ lookup('template', 'interface_edge.cfg.j2') }}"
  tags:
    - develop
    - rendering

- name: Check template rendering result (Core)
  debug:
    msg: "{{ lookup('template', 'interface_core.cfg.j2') }}"
  tags:
    - develop
    - rendering

- name: Update interface configurations (Edge)
  connection: netconf
  junos_config:
    src: interface_edge.cfg.j2
    src_format: set
    comment: Action performed by ansible
    confirm: 0
    update: merge
  when: "'EDGE-SW' in group_names"

- name: Update interface configurations (Core)
  connection: netconf
  junos_config:
    src: interface_core.cfg.j2
    src_format: set
    comment: Action performed by ansible
    confirm: 0
    update: merge
  when: "'CORE-SW' in group_names"

- name: Create post-snapshots
  connection: netconf
  junos_config:
    backup: yes
    backup_options:
      filename: "{{ hostname }}_after.cfg"
      dir_path: "backup/juniper_config.{{ datetime }}"
  tags:
    - nondry
