---
- name: Display all variables and facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags:
    - develop

- name: Show version
  connection: network_cli
  junos_command:
    commands: show version
  tags:
    - develop

- name: Enable NETCONF
  connection: network_cli
  junos_netconf:

- name: Create pre snapshots
  connection: netconf
  junos_config:
    backup: yes
    backup_options:
      filename: "{{ hostname }}_before.cfg"
      dir_path: backup/config.{{ datetime }}

- name: Check template rendering result
  debug:
    msg: "{{ lookup('template', 'config.j2') }}"
  tags:
    - develop

- name: Create VLANs and update interface settings
  connection: netconf
  junos_config:
    src: config.j2
    src_format: set
    comment: Action performed by ansible
    update: merge

- name: Create post snapshots
  connection: netconf
  junos_config:
    backup: yes
    backup_options:
      filename: "{{ hostname }}_after.cfg"
      dir_path: backup/config.{{ datetime }}
